apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mysql-db-pv
spec:
  capacity:
    storage: 1Gi
    accessModes:
      - ReadWriteOnce
    hostsPath:
      path: /data/db